services:
  - type: web
    name: voice-ai-backend
    env: python
    region: oregon
    branch: main
    buildCommand: ""
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 10000
    plan: free
    envVars:
      - key: GOOGLE_API_KEY
        value: your-gemini-api-key-here
      - key: PORT
        value: 10000
